# Generated by Django 5.1.12 on 2025-09-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(default="", max_length=100)),
                ("position", models.CharField(default="", max_length=50)),
                ("games", models.IntegerField(default=0)),
                ("at_bat", models.IntegerField(default=0)),
                ("runs", models.IntegerField(default=0)),
                ("hits", models.IntegerField(default=0)),
                ("double_2b", models.IntegerField(default=0)),
                ("third_baseman", models.IntegerField(default=0)),
                ("home_run", models.IntegerField(default=0)),
                ("run_batted_in", models.IntegerField(default=0)),
                ("a_walk", models.IntegerField(default=0)),
                ("strikeouts", models.IntegerField(default=0)),
                ("stolen_base", models.IntegerField(default=0)),
                ("caught_stealing", models.IntegerField(default=0)),
                ("avg", models.FloatField(default=0)),
                ("on_base_percentage", models.FloatField(default=0)),
                ("slugging_percentage", models.FloatField(default=0)),
                ("on_base_plus_slugging", models.FloatField(default=0)),
            ],
            options={
                "db_table": "player",
            },
        ),
    ]
